# Generated by Django 3.2.16 on 2022-12-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_social_stackoverflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
    ]
