# Generated by Django 3.2.16 on 2023-01-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_message_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, default='Dave', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, default='Message', max_length=200),
            preserve_default=False,
        ),
    ]
