# Generated by Django 3.2.16 on 2022-12-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='assets/default.jpg', null=True, upload_to=''),
        ),
    ]
